# coding: utf-8
"""Waylay Storage: REST Models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

version: 0.9.0

 Manage storage buckets and subscriptions.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "0.9.0.20251218"

# import models into model package
from .auth import AUTH
from .authentication_config import AuthenticationConfig
from .bucket import Bucket
from .bucket_configuration import BucketConfiguration
from .bucket_listing import BucketListing
from .bucket_object import BucketObject
from .bucket_object_listing import BucketObjectListing
from .bucketcreationstatus import BUCKETCREATIONSTATUS
from .bucketpolicystatus import BUCKETPOLICYSTATUS
from .channel import Channel
from .channel1 import Channel1
from .channeltype import CHANNELTYPE
from .event_filter import EventFilter
from .expiry import Expiry
from .hal_entity import HALEntity
from .hal_link import HALLink
from .http_validation_error import HTTPValidationError
from .httpmethod import HTTPMETHOD
from .links_value import LinksValue
from .location_inner import LocationInner
from .notification_queue_status import NotificationQueueStatus
from .notification_queue_status_report import NotificationQueueStatusReport
from .payload_config import PayloadConfig
from .queuesetupstatus import QUEUESETUPSTATUS
from .resource import Resource
from .response_list_object import ResponseListObject
from .s3_policy_def import S3PolicyDef
from .s3_policy_statement import S3PolicyStatement
from .sign import SIGN
from .store import Store
from .storetype import STORETYPE
from .subscription_config_input import SubscriptionConfigInput
from .subscription_config_output import SubscriptionConfigOutput
from .subscriptions import Subscriptions
from .subscriptions_listing import SubscriptionsListing
from .system_channel_config_input import SystemChannelConfigInput
from .system_channel_config_input_type import SystemChannelConfigInputType
from .system_channel_config_output import SystemChannelConfigOutput
from .tenant_status_report import TenantStatusReport
from .validation_error import ValidationError
from .venttype import VENTTYPE
from .web_script_channel_config_input import WebScriptChannelConfigInput
from .web_script_channel_config_input_type import WebScriptChannelConfigInputType
from .web_script_channel_config_output import WebScriptChannelConfigOutput

__all__ = [
    "__version__",
    "AUTH",
    "AuthenticationConfig",
    "BUCKETCREATIONSTATUS",
    "BUCKETPOLICYSTATUS",
    "Bucket",
    "BucketConfiguration",
    "BucketListing",
    "BucketObject",
    "BucketObjectListing",
    "CHANNELTYPE",
    "Channel",
    "Channel1",
    "EventFilter",
    "Expiry",
    "HALEntity",
    "HALLink",
    "HTTPMETHOD",
    "HTTPValidationError",
    "LinksValue",
    "LocationInner",
    "NotificationQueueStatus",
    "NotificationQueueStatusReport",
    "PayloadConfig",
    "QUEUESETUPSTATUS",
    "Resource",
    "ResponseListObject",
    "S3PolicyDef",
    "S3PolicyStatement",
    "SIGN",
    "STORETYPE",
    "Store",
    "SubscriptionConfigInput",
    "SubscriptionConfigOutput",
    "Subscriptions",
    "SubscriptionsListing",
    "SystemChannelConfigInput",
    "SystemChannelConfigInputType",
    "SystemChannelConfigOutput",
    "TenantStatusReport",
    "VENTTYPE",
    "ValidationError",
    "WebScriptChannelConfigInput",
    "WebScriptChannelConfigInputType",
    "WebScriptChannelConfigOutput",
]
