# coding: utf-8
"""Waylay Storage: REST Models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

version: 0.4.1

 Manage storage buckets and subscriptions.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "0.4.1.20240423"

# import models into model package
from .auth import AUTH
from .authentication_config import AuthenticationConfig
from .bucket import Bucket
from .bucket_configuration import BucketConfiguration
from .bucket_listing import BucketListing
from .bucket_object import BucketObject
from .bucket_object_listing import BucketObjectListing
from .bucketcreationstatus import BUCKETCREATIONSTATUS
from .bucketpolicystatus import BUCKETPOLICYSTATUS
from .channel import Channel
from .channeltype import CHANNELTYPE
from .event_filter import EventFilter
from .expiry import Expiry
from .hal_entity import HALEntity
from .hal_link import HALLink
from .http_validation_error import HTTPValidationError
from .httpmethod import HTTPMETHOD
from .links import Links
from .location_inner import LocationInner
from .notification_queue_status import NotificationQueueStatus
from .notification_queue_status_report import NotificationQueueStatusReport
from .payload_config import PayloadConfig
from .queuesetupstatus import QUEUESETUPSTATUS
from .response_list import ResponseList
from .sign import SIGN
from .store import Store
from .storetype import STORETYPE
from .subscription_config import SubscriptionConfig
from .subscriptions import Subscriptions
from .subscriptions_listing import SubscriptionsListing
from .system_channel_config import SystemChannelConfig
from .system_channel_config_type import SystemChannelConfigType
from .tenant_status_report import TenantStatusReport
from .validation_error import ValidationError
from .venttype import VENTTYPE
from .web_script_channel_config import WebScriptChannelConfig
from .web_script_channel_config_type import WebScriptChannelConfigType

__all__ = [
    "__version__",
    "AUTH",
    "AuthenticationConfig",
    "BUCKETCREATIONSTATUS",
    "BUCKETPOLICYSTATUS",
    "Bucket",
    "BucketConfiguration",
    "BucketListing",
    "BucketObject",
    "BucketObjectListing",
    "CHANNELTYPE",
    "Channel",
    "EventFilter",
    "Expiry",
    "HALEntity",
    "HALLink",
    "HTTPMETHOD",
    "HTTPValidationError",
    "Links",
    "LocationInner",
    "NotificationQueueStatus",
    "NotificationQueueStatusReport",
    "PayloadConfig",
    "QUEUESETUPSTATUS",
    "ResponseList",
    "SIGN",
    "STORETYPE",
    "Store",
    "SubscriptionConfig",
    "Subscriptions",
    "SubscriptionsListing",
    "SystemChannelConfig",
    "SystemChannelConfigType",
    "TenantStatusReport",
    "VENTTYPE",
    "ValidationError",
    "WebScriptChannelConfig",
    "WebScriptChannelConfigType",
]
