# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import Dict

from pydantic import (
    ConfigDict,
    Field,
    StrictInt,
    StrictStr,
)

from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.links_value import LinksValue
from ..models.store import Store


class Bucket(WaylayBaseModel):
    """Representation of a storage bucket.."""

    links: Dict[str, LinksValue] | None = Field(default=None, alias="_links")
    alias: StrictStr | None = None
    name: StrictStr
    store: Store | None = None
    creation_date: datetime | None = None
    size: StrictInt | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
