# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Dict, List

from pydantic import (
    ConfigDict,
    Field,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.bucket_object import BucketObject
from ..models.links_value import LinksValue


class BucketObjectListing(WaylayBaseModel):
    """List of storage object representations.."""

    links: Dict[str, LinksValue] | None = Field(default=None, alias="_links")
    objects: List[BucketObject]

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
