# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from pydantic import (
    ConfigDict,
    Field,
    StrictInt,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.bucketcreationstatus import BUCKETCREATIONSTATUS
from ..models.links import Links
from ..models.store import Store


class BucketConfiguration(WaylayBaseModel):
    """Representation of a bucket configuration.."""

    links: Dict[str, Links] | None = Field(default=None, alias="_links")
    alias: StrictStr | None = None
    name: StrictStr
    store: Store | None = None
    creation_date: datetime | None = None
    size: StrictInt | None = None
    status: BUCKETCREATIONSTATUS | None = None
    public_policy_json: Dict[str, Any] | None = None
    public_policy_type: StrictStr | None = None
    error: StrictStr | None = None

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
