# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from ..models.system_channel_config import SystemChannelConfig
from ..models.web_script_channel_config import WebScriptChannelConfig

from typing import (
    Union,
    Any,
    List,
    TYPE_CHECKING,
    Optional,
    Dict,
    Literal,  # >=3.8
)
from typing_extensions import (
    Annotated,  # >=3.9
)

from pydantic import StrictStr, Field, ConfigDict

Channel = Union[
    Annotated[WebScriptChannelConfig, ""], Annotated[SystemChannelConfig, ""]
]
"""Channel."""
