# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import Annotated

from ..models.system_channel_config import SystemChannelConfig
from ..models.web_script_channel_config import WebScriptChannelConfig

Channel = Union[
    Annotated[WebScriptChannelConfig, ""], Annotated[SystemChannelConfig, ""]
]
"""Channel."""
