# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Union

from typing_extensions import Annotated

from ..models.system_channel_config_output import SystemChannelConfigOutput
from ..models.web_script_channel_config_output import WebScriptChannelConfigOutput

Channel1 = Union[
    Annotated[WebScriptChannelConfigOutput, ""],
    Annotated[SystemChannelConfigOutput, ""],
]
"""Channel1."""
