# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import List, Union

from typing_extensions import Annotated

Resource = Union[Annotated[str, ""], Annotated[List[str], ""]]
"""Resource."""
