# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Union

from typing_extensions import Annotated

from ..models.bucket_object import BucketObject
from ..models.bucket_object_listing import BucketObjectListing
from ..models.hal_entity import HALEntity

ResponseListObject = Union[
    Annotated[BucketObjectListing, ""],
    Annotated[BucketObject, ""],
    Annotated[HALEntity, ""],
]
"""ResponseListObject."""
