# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class SIGN(str, Enum):
    """Supported `sign` url parameter values.."""

    GET = "GET"
    PUT = "PUT"
    POST = "POST"

    def __str__(self) -> str:
        return str(self.value)
