# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Dict

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)

from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.links_value import LinksValue
from ..models.storetype import STORETYPE


class Store(WaylayBaseModel):
    """Representation of a backend store.."""

    links: Dict[str, LinksValue] | None = Field(default=None, alias="_links")
    type: STORETYPE
    name: StrictStr
    url: StrictStr

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
