# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class STORETYPE(str, Enum):
    """Supported backend store types.."""

    GS = "gs"
    S3 = "s3"
    AZURE = "azure"

    def __str__(self) -> str:
        return str(self.value)
