# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import Dict, List

from pydantic import (
    ConfigDict,
    Field,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.channel import Channel
from ..models.event_filter import EventFilter
from ..models.links_value import LinksValue


class SubscriptionConfig(WaylayBaseModel):
    """Specification of a notification subscription that forwards to a given channel.."""

    links: Dict[str, LinksValue] | None = Field(default=None, alias="_links")
    id: StrictStr | None = None
    title: StrictStr | None = None
    description: StrictStr | None = None
    channel: Channel
    filters: List[EventFilter]

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
