# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.authentication_config import AuthenticationConfig
from ..models.expiry import Expiry
from ..models.payload_config import PayloadConfig
from ..models.system_channel_config_type import SystemChannelConfigType


class SystemChannelConfig(WaylayBaseModel):
    """Channel configuration for functionality that is fixed by the platform.  This cannot be selected by the end user.."""

    type: SystemChannelConfigType | None = None
    description: StrictStr | None = None
    payload: PayloadConfig | None = None
    authentication: AuthenticationConfig | None = None
    expiry: Expiry | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
