# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.authentication_config import AuthenticationConfig
from ..models.expiry import Expiry
from ..models.httpmethod import HTTPMETHOD
from ..models.payload_config import PayloadConfig
from ..models.web_script_channel_config_input_type import (
    WebScriptChannelConfigInputType,
)


class WebScriptChannelConfigInput(WaylayBaseModel):
    """Channel configuration for invoking a waylay webscript.."""

    type: WebScriptChannelConfigInputType | None = (
        WebScriptChannelConfigInputType.WEBSCRIPT
    )
    description: StrictStr | None = None
    payload: PayloadConfig | None = None
    authentication: AuthenticationConfig | None = None
    expiry: Expiry | None = None
    name: StrictStr
    version: StrictStr | None = None
    method: HTTPMETHOD | None = None

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
