# coding: utf-8
"""Waylay Storage models.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    StrictStr,
)
from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.authentication_config import AuthenticationConfig
from ..models.expiry import Expiry
from ..models.httpmethod import HTTPMETHOD
from ..models.payload_config import PayloadConfig
from ..models.web_script_channel_config_type import WebScriptChannelConfigType


class WebScriptChannelConfig(WaylayBaseModel):
    """Channel configuration for invoking a waylay webscript.."""

    type: WebScriptChannelConfigType | None = None
    description: StrictStr | None = None
    payload: PayloadConfig | None = None
    authentication: AuthenticationConfig | None = None
    expiry: Expiry | None = None
    name: StrictStr
    version: StrictStr | None = None
    method: HTTPMETHOD | None = None

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
