# coding: utf-8
"""Waylay Storage: Query Parameters.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

version: 0.4.1

 Manage storage buckets and subscriptions.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""
