"""Waylay Storage: Service.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

version: 0.9.0

 Manage storage buckets and subscriptions.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "0.9.0rc20260304"

from .service import StorageService

PLUGINS = [StorageService]

__all__ = [
    "__version__",
    "StorageService",
]
