# coding: utf-8
"""Waylay Storage: Service.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

version: 0.5.2

 Manage storage buckets and subscriptions.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "0.5.2.20241025"

from .service import StorageService

PLUGINS = [StorageService]

__all__ = [
    "__version__",
    "StorageService",
]
