# coding: utf-8
"""Waylay Storage: Service.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

version: v0.4.0

 Manage storage buckets and subscriptions.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

__version__ = "v0.4.0-0"

from .service import StorageService

PLUGINS = [StorageService]

__all__ = [
    "__version__",
    "StorageService",
]
