# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.authentication_config import (
        AuthenticationConfig,
    )

    AuthenticationConfigAdapter = TypeAdapter(AuthenticationConfig)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

authentication_config_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "method" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/AUTH"
      } ],
      "default" : "DEFAULT"
    },
    "key" : {
      "title" : "Key",
      "type" : "string"
    },
    "secret" : {
      "title" : "Secret",
      "type" : "string"
    }
  },
  "description" : "Configuration for the authentication method used when forwarding an event to a channel."
}
""",
    object_hook=with_example_provider,
)
authentication_config_model_schema.update({"definitions": MODEL_DEFINITIONS})

authentication_config_faker = JSF(
    authentication_config_model_schema, allow_none_optionals=1
)


class AuthenticationConfigStub:
    """AuthenticationConfig unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return authentication_config_faker.generate()

    @classmethod
    def create_instance(cls) -> "AuthenticationConfig":
        """Create AuthenticationConfig stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AuthenticationConfigAdapter.validate_python(cls.create_json())
