# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.bucketpolicystatus import BUCKETPOLICYSTATUS

    BUCKETPOLICYSTATUSAdapter = TypeAdapter(BUCKETPOLICYSTATUS)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

bucket_policy_status_model_schema = json.loads(
    r"""{
  "type" : "string",
  "description" : "Possible bucket policy status codes.",
  "enum" : [ "unknown", "missing", "out_dated", "up_to_date" ]
}
""",
    object_hook=with_example_provider,
)
bucket_policy_status_model_schema.update({"definitions": MODEL_DEFINITIONS})

bucket_policy_status_faker = JSF(
    bucket_policy_status_model_schema, allow_none_optionals=1
)


class BUCKETPOLICYSTATUSStub:
    """BUCKETPOLICYSTATUS unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return bucket_policy_status_faker.generate()

    @classmethod
    def create_instance(cls) -> "BUCKETPOLICYSTATUS":
        """Create BUCKETPOLICYSTATUS stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BUCKETPOLICYSTATUSAdapter.validate_python(cls.create_json())
