# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.bucket_object_listing import BucketObjectListing

    BucketObjectListingAdapter = TypeAdapter(BucketObjectListing)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

bucket_object_listing_model_schema = json.loads(
    r"""{
  "required" : [ "objects" ],
  "type" : "object",
  "properties" : {
    "_links" : {
      "title" : " Links",
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/components/schemas/_Links"
      }
    },
    "objects" : {
      "title" : "Objects",
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/BucketObject"
      }
    }
  },
  "description" : "List of storage object representations."
}
""",
    object_hook=with_example_provider,
)
bucket_object_listing_model_schema.update({"definitions": MODEL_DEFINITIONS})

bucket_object_listing_faker = JSF(
    bucket_object_listing_model_schema, allow_none_optionals=1
)


class BucketObjectListingStub:
    """BucketObjectListing unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return bucket_object_listing_faker.generate()

    @classmethod
    def create_instance(cls) -> "BucketObjectListing":
        """Create BucketObjectListing stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BucketObjectListingAdapter.validate_python(cls.create_json())
