# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.bucket_configuration import BucketConfiguration

    BucketConfigurationAdapter = TypeAdapter(BucketConfiguration)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

bucket_configuration_model_schema = json.loads(
    r"""{
  "required" : [ "name" ],
  "type" : "object",
  "properties" : {
    "_links" : {
      "title" : " Links",
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/components/schemas/_Links"
      }
    },
    "alias" : {
      "title" : "Alias",
      "type" : "string"
    },
    "name" : {
      "title" : "Name",
      "type" : "string"
    },
    "store" : {
      "$ref" : "#/components/schemas/Store"
    },
    "creation_date" : {
      "title" : "Creation Date",
      "type" : "string",
      "format" : "date-time"
    },
    "size" : {
      "title" : "Size",
      "type" : "integer"
    },
    "status" : {
      "allOf" : [ {
        "$ref" : "#/components/schemas/BUCKET_CREATION_STATUS"
      } ],
      "default" : "unknown"
    },
    "public_policy_json" : {
      "title" : "Public Policy Json",
      "type" : "object"
    },
    "public_policy_type" : {
      "title" : "Public Policy Type",
      "type" : "string"
    },
    "error" : {
      "title" : "Error",
      "type" : "string"
    }
  },
  "description" : "Representation of a bucket configuration."
}
""",
    object_hook=with_example_provider,
)
bucket_configuration_model_schema.update({"definitions": MODEL_DEFINITIONS})

bucket_configuration_faker = JSF(
    bucket_configuration_model_schema, allow_none_optionals=1
)


class BucketConfigurationStub:
    """BucketConfiguration unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return bucket_configuration_faker.generate()

    @classmethod
    def create_instance(cls) -> "BucketConfiguration":
        """Create BucketConfiguration stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return BucketConfigurationAdapter.validate_python(cls.create_json())
