# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.channeltype import CHANNELTYPE

    CHANNELTYPEAdapter = TypeAdapter(CHANNELTYPE)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

channel_type_model_schema = json.loads(
    r"""{
  "type" : "string",
  "description" : "Supported notification channel types.",
  "enum" : [ "webhook", "webscript", "system" ]
}
""",
    object_hook=with_example_provider,
)
channel_type_model_schema.update({"definitions": MODEL_DEFINITIONS})

channel_type_faker = JSF(channel_type_model_schema, allow_none_optionals=1)


class CHANNELTYPEStub:
    """CHANNELTYPE unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return channel_type_faker.generate()

    @classmethod
    def create_instance(cls) -> "CHANNELTYPE":
        """Create CHANNELTYPE stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return CHANNELTYPEAdapter.validate_python(cls.create_json())
