# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.channel1 import Channel1

    Channel1Adapter = TypeAdapter(Channel1)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

channel_1_model_schema = json.loads(
    r"""{
  "title" : "Channel",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/WebScriptChannelConfig-Output"
  }, {
    "$ref" : "#/components/schemas/SystemChannelConfig-Output"
  } ]
}
""",
    object_hook=with_example_provider,
)
channel_1_model_schema.update({"definitions": MODEL_DEFINITIONS})

channel_1_faker = JSF(channel_1_model_schema, allow_none_optionals=1)


class Channel1Stub:
    """Channel1 unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return channel_1_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "Channel1":
        """Create Channel1 stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(Channel1Adapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return Channel1Adapter.validate_python(json, context={"skip_validation": True})
