# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.hal_link import HALLink

    HALLinkAdapter = TypeAdapter(HALLink)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

hal_link_model_schema = json.loads(
    r"""{
  "required" : [ "href" ],
  "type" : "object",
  "properties" : {
    "href" : {
      "title" : "Href",
      "type" : "string"
    },
    "method" : {
      "title" : "Method",
      "type" : "string"
    },
    "form_data" : {
      "title" : "Form Data",
      "type" : "object"
    }
  },
  "description" : "Represents a HAL link."
}
""",
    object_hook=with_example_provider,
)
hal_link_model_schema.update({"definitions": MODEL_DEFINITIONS})

hal_link_faker = JSF(hal_link_model_schema, allow_none_optionals=1)


class HALLinkStub:
    """HALLink unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return hal_link_faker.generate()

    @classmethod
    def create_instance(cls) -> "HALLink":
        """Create HALLink stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return HALLinkAdapter.validate_python(cls.create_json())
