# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.notification_queue_status import (
        NotificationQueueStatus,
    )

    NotificationQueueStatusAdapter = TypeAdapter(NotificationQueueStatus)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

notification_queue_status_model_schema = json.loads(
    r"""{
  "required" : [ "method", "name", "status" ],
  "type" : "object",
  "properties" : {
    "status" : {
      "$ref" : "#/components/schemas/QUEUE_SETUP_STATUS"
    },
    "name" : {
      "title" : "Name",
      "type" : "string"
    },
    "method" : {
      "title" : "Method",
      "type" : "string"
    },
    "configured_parameters" : {
      "title" : "Configured Parameters",
      "type" : "object",
      "additionalProperties" : true
    },
    "actual_parameters" : {
      "title" : "Actual Parameters",
      "type" : "object",
      "additionalProperties" : true
    },
    "error" : {
      "title" : "Error",
      "type" : "string"
    }
  },
  "description" : "Response model for the notification queue configuration."
}
""",
    object_hook=with_example_provider,
)
notification_queue_status_model_schema.update({"definitions": MODEL_DEFINITIONS})

notification_queue_status_faker = JSF(
    notification_queue_status_model_schema, allow_none_optionals=1
)


class NotificationQueueStatusStub:
    """NotificationQueueStatus unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return notification_queue_status_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "NotificationQueueStatus":
        """Create NotificationQueueStatus stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                NotificationQueueStatusAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return NotificationQueueStatusAdapter.validate_python(
            json, context={"skip_validation": True}
        )
