# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.payload_config import PayloadConfig

    PayloadConfigAdapter = TypeAdapter(PayloadConfig)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

payload_config_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "signed_links" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/SIGN"
      }
    },
    "reference" : {
      "title" : "Reference"
    }
  },
  "description" : "Configuration object that specifies the expected notification payload."
}
""",
    object_hook=with_example_provider,
)
payload_config_model_schema.update({"definitions": MODEL_DEFINITIONS})

payload_config_faker = JSF(payload_config_model_schema, allow_none_optionals=1)


class PayloadConfigStub:
    """PayloadConfig unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return payload_config_faker.generate()

    @classmethod
    def create_instance(cls) -> "PayloadConfig":
        """Create PayloadConfig stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PayloadConfigAdapter.validate_python(cls.create_json())
