# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.response_list import ResponseList

    ResponseListAdapter = TypeAdapter(ResponseList)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

response_list_model_schema = json.loads(
    r"""{
  "title" : "Response List",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/BucketObjectListing"
  }, {
    "$ref" : "#/components/schemas/BucketObject"
  }, {
    "$ref" : "#/components/schemas/HALEntity"
  } ]
}
""",
    object_hook=with_example_provider,
)
response_list_model_schema.update({"definitions": MODEL_DEFINITIONS})

response_list_faker = JSF(response_list_model_schema, allow_none_optionals=1)


class ResponseListStub:
    """ResponseList unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return response_list_faker.generate()

    @classmethod
    def create_instance(cls) -> "ResponseList":
        """Create ResponseList stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return ResponseListAdapter.validate_python(cls.create_json())
