# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.s3_policy_def import S3PolicyDef

    S3PolicyDefAdapter = TypeAdapter(S3PolicyDef)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

s3_policy_def_model_schema = json.loads(
    r"""{
  "title" : "S3PolicyDef",
  "type" : "object",
  "properties" : {
    "Statement" : {
      "title" : "Statement",
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/S3PolicyStatement"
      }
    },
    "Version" : {
      "title" : "Version",
      "type" : "string"
    }
  },
  "additionalProperties" : true,
  "description" : "AWS S3 Policy definition."
}
""",
    object_hook=with_example_provider,
)
s3_policy_def_model_schema.update({"definitions": MODEL_DEFINITIONS})

s3_policy_def_faker = JSF(s3_policy_def_model_schema, allow_none_optionals=1)


class S3PolicyDefStub:
    """S3PolicyDef unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return s3_policy_def_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "S3PolicyDef":
        """Create S3PolicyDef stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(S3PolicyDefAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return S3PolicyDefAdapter.validate_python(
            json, context={"skip_validation": True}
        )
