# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.s3_policy_statement import S3PolicyStatement

    S3PolicyStatementAdapter = TypeAdapter(S3PolicyStatement)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

s3_policy_statement_model_schema = json.loads(
    r"""{
  "title" : "S3PolicyStatement",
  "type" : "object",
  "properties" : {
    "Resource" : {
      "$ref" : "#/components/schemas/Resource"
    }
  },
  "additionalProperties" : true,
  "description" : "AWS S3 Policy definition statement."
}
""",
    object_hook=with_example_provider,
)
s3_policy_statement_model_schema.update({"definitions": MODEL_DEFINITIONS})

s3_policy_statement_faker = JSF(
    s3_policy_statement_model_schema, allow_none_optionals=1
)


class S3PolicyStatementStub:
    """S3PolicyStatement unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return s3_policy_statement_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "S3PolicyStatement":
        """Create S3PolicyStatement stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                S3PolicyStatementAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return S3PolicyStatementAdapter.validate_python(
            json, context={"skip_validation": True}
        )
