# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import datetime
import json
import warnings

from typing import (
    Union,
    List,
    Dict,
    Literal,  # >=3.8
)
from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.storetype import STORETYPE

    STORETYPEAdapter = TypeAdapter(STORETYPE)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

store_type_model_schema = json.loads(
    r"""{
  "title" : "STORE_TYPE",
  "type" : "string",
  "description" : "Supported backend store types.",
  "enum" : [ "gs", "s3", "azure" ]
}
""",
    object_hook=with_example_provider,
)
store_type_model_schema.update({"definitions": MODEL_DEFINITIONS})

store_type_faker = JSF(store_type_model_schema, allow_none_optionals=1)


class STORETYPEStub:
    """STORETYPE unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return store_type_faker.generate()

    @classmethod
    def create_instance(cls) -> "STORETYPE":
        """Create STORETYPE stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return STORETYPEAdapter.validate_python(cls.create_json())
