# coding: utf-8
"""Waylay Storage model tests.

This code was generated from the OpenAPI documentation of 'Waylay Storage'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.storage.models.subscription_config_input import (
        SubscriptionConfigInput,
    )

    SubscriptionConfigInputAdapter = TypeAdapter(SubscriptionConfigInput)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

subscription_config_input_model_schema = json.loads(
    r"""{
  "required" : [ "channel", "filters" ],
  "type" : "object",
  "properties" : {
    "_links" : {
      "title" : "Links",
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/components/schemas/Links_value"
      }
    },
    "id" : {
      "title" : "Id",
      "type" : "string"
    },
    "title" : {
      "title" : "Title",
      "type" : "string"
    },
    "description" : {
      "title" : "Description",
      "type" : "string"
    },
    "channel" : {
      "$ref" : "#/components/schemas/Channel"
    },
    "filters" : {
      "title" : "Filters",
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/EventFilter"
      }
    }
  },
  "description" : "Specification of a notification subscription that forwards to a given channel."
}
""",
    object_hook=with_example_provider,
)
subscription_config_input_model_schema.update({"definitions": MODEL_DEFINITIONS})

subscription_config_input_faker = JSF(
    subscription_config_input_model_schema, allow_none_optionals=1
)


class SubscriptionConfigInputStub:
    """SubscriptionConfigInput unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return subscription_config_input_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "SubscriptionConfigInput":
        """Create SubscriptionConfigInput stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                SubscriptionConfigInputAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return SubscriptionConfigInputAdapter.validate_python(
            json, context={"skip_validation": True}
        )
